### ISSUE TITLE
Entity Links Not Working

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm-web#12]
Where I click on the links to open the respective tables for STR entities (Farmer and Garden) in the dashboard, nothing happens. 

![image](https://user-images.githubusercontent.com/3840267/115888308-72cdc800-a45b-11eb-9479-bc8f08404980.png)

**Comment by wanjohikibui** [comment]
The issue has been resolved. All Entity Links are now working

**Comment by gkahiu** [comment]
Has this been pushed to the public website because **Farmer** and **Garden** are still not working. 

Seems like it applies for those participating in an STR are the ones affected.

**Comment by gkahiu** [comment]
Still not working for Garden (spatial unit)

![image](https://user-images.githubusercontent.com/3840267/124878952-59a5d380-dfd5-11eb-8de9-e4e49c56d2bf.png)

**Comment by gkahiu** [comment]
Am still encountering this when switching from KOPGT to Rural-Agriculture.
