### ISSUE TITLE
Incorrect Table Column Placement 

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm-web#23]
Some column headers appear misplaced such that they show values for a different column.

**Comment by wanjohikibui** [comment]
This issue has been sorted

**Comment by wanjohikibui** [comment]
![sorted](https://user-images.githubusercontent.com/4972951/183891766-2a0a6ab1-f7fb-4c81-ba0d-24f60fc84103.png)
Has been sorted

**Comment by gkahiu** [comment]
![image](https://user-images.githubusercontent.com/3840267/184177686-e82896b5-2cc4-4c5f-a949-eaa1f62104ea.png)

Not consistent for all columns, see the ones marked with the red vertical line where the column header seems to be centre-aligned however the row text seems to be left-aligned or the centre-reference is not the same.

**Comment by wanjohikibui** [comment]
This issue has been resolved. Was caused by a typo in the css files
![sorted_table](https://user-images.githubusercontent.com/4972951/184339905-63019845-808d-41e9-8ec7-8ab97d4352e2.png)

**Comment by gkahiu** [comment]
> ![image](https://user-images.githubusercontent.com/3840267/184177686-e82896b5-2cc4-4c5f-a949-eaa1f62104ea.png)
> 
> Not consistent for all columns, see the ones marked with the red vertical line where the column header seems to be centre-aligned however the row text seems to be left-aligned or the centre-reference is not the same.

This issue still persists. I have tried to refresh and using different browsers still shows the centre misalignment.

**Comment by wanjohikibui** [comment]
This issue is now sorted
![datafine](https://user-images.githubusercontent.com/4972951/185199145-f5cf5c4b-7269-4f32-8c0c-c3f2bf4755c4.png)
